name: Block Pull Requests for non-Ready Jira Tickets

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-ticket-status:
    runs-on: ubuntu-latest
    steps:
      - name: Get Jira ticket ID
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
          JIRA_URL: https://your-jira-url.com/
        run: |
          pr_url=$(jq -r .pull_request.url "$GITHUB_EVENT_PATH")
          pr_branch=$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")
          ticket_id=$(curl -u $JIRA_USERNAME:$JIRA_PASSWORD -H "Content-Type: application/json" -X GET "$JIRA_URL/rest/dev-status/1.0/issue/detail?issueId=$pr_url&applicationType=github&dataType=pullrequest" | jq -r '.detail[].issue.key')
          echo "Ticket ID: $ticket_id"
          if [ -z "$ticket_id" ]; then
            echo "Failed to retrieve ticket ID from Jira. Aborting."
            exit 1
          fi
      - name: Check Jira ticket status
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
          JIRA_URL: https://your-jira-url.com/
        run: |
          ticket_status=$(curl -u $JIRA_USERNAME:$JIRA_PASSWORD -H "Content-Type: application/json" $JIRA_URL/rest/api/3/issue/$ticket_id | jq '.fields.status.name')
          if [ "$ticket_status" != "\"Ready\"" ]; then
            echo "Ticket is not ready for merge. Aborting."
            exit 1
          fi
